<?php
    get_header();
    ?>
        <main>
            <?php
                get_template_part('content');
                get_sidebar();
            ?>
        </main>
    <?php
    get_footer();
?>
